name: Build and Deploy

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.9.0]

        steps:
            - uses: actions/checkout@latest
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@latest
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm i
            - run: npm run build

            - name: Deploy
              uses: crazy-max/ghaction-github-pages@latest
              with:
                  target_branch: gh-pages
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
